# perform checks on a file
- writing/proposal.md:
    - description: Ensure that the proposal.md file exists in the writing/ directory
      check: ConfirmFileExists
    - description: Complete all TODOs, remove the TODO markers, and rewrite comments for proposal.md
      check: MatchFileFragment
      options:
        fragment: TODO
        count: 0
        exact: true
    - description: Delete the 'Add Your Name Here' prompt in the proposal file
      check: MatchFileFragment
      options:
        fragment: "Add Your Name Here"
        count: 0
        exact: true
    - description: Preserve the list of checks for tasks designated for completion during this project
      check: MatchFileFragment
      options:
        fragment: "- ["
        count: 7
        exact: false
    - description: Indicate your completion of the tasks in the proposal checklist
      check: MatchFileFragment
      options:
        fragment: "- [X]"
        count: 8
        exact: false
    - description: Provide a statement of your chosen project with the correct label
      check: MatchFileFragment
      options:
        fragment: "**Final Topic**"
        count: 1
        exact: false
    - description: Write a minimum number of meaningful words in the proposal document
      check: CountFileWords
      options:
        count: 1000
        exact: false
    - description: Confirm that the markdown file has at least a minimum number of headers
      check: CountMarkdownTags
      options:
        tag: heading
        count: 15
        exact: false
    - description: Confirm that the proposal.md markdown file has at least seven check lists
      check: CountMarkdownTags
      options:
        tag: list 
        count: 7
        exact: false

# confirm a suitable number of commit messages
- description: Have at least a specific minimum of commits in repository
  check: CountCommits
  options:
    count: 5
